name: Cypress Tests

on:
  push:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm test

      - name: Fetch Current one Job URL
        id: url
        run: |
          # The current workflow run ID
          CURRENT_RUN_ID=$GITHUB_RUN_ID
          echo "Current Run ID: $CURRENT_RUN_ID"
          
          # Construct the URL for the current job
          if [ "$CURRENT_RUN_ID" != "null" -a "$CURRENT_RUN_ID" != "" ]; then
            CURRENT_JOB_URL="https://github.com/$GITHUB_REPOSITORY/actions/runs/$CURRENT_RUN_ID"
            echo "current_job_url=$CURRENT_JOB_URL" >> "$GITHUB_OUTPUT"
          
          else
            echo "⛔️ Failed to retrieve the current workflow run ID"
            exit 1
          fi

      - name: Print info
        run: |
          echo "Current job Url ---> ${{ steps.url.outputs.current_job_url }}"

      - name: Print and Use Test Results
        id: test_results
        run: |
          report=$(cat cypress/report/combined-report.json)
          total_tests=$(echo $report | jq '.stats.tests')
          passed=$(echo $report | jq '.stats.passes')
          failed=$(echo $report | jq '.stats.failures')
          skipped=$(echo $report | jq '.stats.pending')
          
          echo "Total Tests: $total_tests"
          echo "Passed: $passed"
          echo "Failed: $failed"
          echo "Skipped: $skipped"
          
          if [ "$total_tests" -eq 0 ]; then
            success_rate=0
          else
            success_rate=$(awk "BEGIN {printf \"%.2f\", ($passed/$total_tests)*100}")
          fi
          
          echo "total_tests=$total_tests" >> "$GITHUB_OUTPUT"
          echo "passed=$passed" >> "$GITHUB_OUTPUT"
          echo "failed=$failed" >> "$GITHUB_OUTPUT"
          echo "skipped=$skipped" >> "$GITHUB_OUTPUT"
          echo "success_rate=$success_rate" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Action Summary
        if: always()
        run: |
          echo "🔍 **Automated Test Chronicles** 🔍" >> $GITHUB_STEP_SUMMARY
          echo "Behold the saga of our automated tests in vivid detail!" >> $GITHUB_STEP_SUMMARY
          echo "| 📊 Test Metrics | 🎯 Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- | " >> $GITHUB_STEP_SUMMARY
          echo "| 🧮 Total Tests | ${{ steps.test_results.outputs.total_tests }} |" >> $GITHUB_STEP_SUMMARY
          echo "| ✅ Tests Passed | ${{ steps.test_results.outputs.passed }} |" >> $GITHUB_STEP_SUMMARY
          echo "| ❌ Tests Failed | ${{ steps.test_results.outputs.failed }} |" >> $GITHUB_STEP_SUMMARY
          echo "| ⏩ Tests Skipped | ${{ steps.test_results.outputs.skipped }} |" >> $GITHUB_STEP_SUMMARY
          echo "| 📈 Success Rate | ${{ steps.test_results.outputs.success_rate }}% |" >> $GITHUB_STEP_SUMMARY
          

      - name: Slack Message
        if: always()
        id: result
        run: |
          SLACK_MESSAGE_TEXT="Cypress Test Result"        

          SLACK_MESSAGE_PAYLOAD=$(cat << EOF
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "$SLACK_MESSAGE_TEXT",
                  "emoji": true
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The <${{ steps.url.outputs.current_job_url }}|latest test run> has completed. Here are the details:"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "🧪 *Test Suite:* Smoke Test\n\n🔢 *Total Tests:* ${{ steps.test_results.outputs.total_tests }}\n\n✅ *Tests Passed:* ${{ steps.test_results.outputs.passed }}\n\n❌ *Tests Failed:* ${{ steps.test_results.outputs.failed }}\n\n⏩ *Skips:* ${{ steps.test_results.outputs.skipped }}\n\n📈 *Success Rate:* ${{ steps.test_results.outputs.success_rate }}%"
                }
              },
              {
                "type": "divider"
              }
            ]
          }
          EOF
          )

          echo "Sending this payload to Slack: $SLACK_MESSAGE_PAYLOAD"

          curl -X POST -H 'Content-type: application/json' --data "$SLACK_MESSAGE_PAYLOAD" ${{ secrets.SLACK_WEBHOOK }}

      - name: Archive report
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Mocha report
          path: cypress/report/combined-report.html